# Generated by Django 3.1.3 on 2020-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, unique_for_date=True, verbose_name='Date')),
                ('oil_price', models.FloatField(editable=False, null=True, verbose_name='Brent')),
                ('gold_price', models.FloatField(editable=False, null=True, verbose_name='Gold')),
                ('copper_price', models.FloatField(editable=False, null=True, verbose_name='Copper')),
            ],
        ),
    ]
